### ISSUE TITLE
Увеличить покрытие тестами до 30%

### ISSUE THREAD

**Issue by WLM1ke** [WLM1ke/PortfolioOptimizer#12]

**Comment by WLM1ke** [comment]
Достигнуто 39%

**Comment by epogrebnyak** [comment]
Надо исключить из покрытия файлы самых тестов и код ниже if/main:

```python 

if __name__ == '__main__': # pragma: no cover

```

**Comment by epogrebnyak** [comment]
Пример исключения файлов:

https://github.com/mini-kep/parser-rosstat-kep/blob/731fabb4efca5a22df47364ea25c2e05430b63bb/codecov.yml#L1-L8
