### ISSUE TITLE
Unclear nesting for compose_ticker_url_function(ticker)

### ISSUE THREAD

**Issue by epogrebnyak** [WLM1ke/PortfolioOptimizer#19]
Не очень понятно зачем оборачивать функцию ticker_url - видимых выигрышей нет:

https://github.com/WLM1ke/PortfolioOptimizer/blob/c87a3b69355fd583cb975a41d18b9594c0bb46df/src/portfolio/loader_history.py#L38-L49

**Comment by epogrebnyak** [comment]
Также сейчас в конструкторах url много повторяющегося кода, при этом семантически есть похожие составляющие:
- база url
- тикер.json, типа `MCFTRR.json`
- дата начала 
- сдвиг

Можно сделать общий конструктор (функцию) и передавать ему параметры, параметры могут фиксироваться внутри классов.

```
'http://iss.moex.com/iss/history/engines/stock/markets/index/boards/RTSI/securities/MCFTRR.json'
'https://iss.moex.com/iss/history/engines/stock/markets/shares/securities/{ticker}.json'
```

**Comment by WLM1ke** [comment]
[Реализовано](https://github.com/WLM1ke/PortfolioOptimizer/commit/da2cf6197f716fbae449c98fd8aab88f0d0d60a0)
