### ISSUE TITLE
cleanup Ticket dataframe construction

### ISSUE THREAD

**Issue by epogrebnyak** [WLM1ke/PortfolioOptimizer#20]
https://github.com/WLM1ke/PortfolioOptimizer/blob/8d55dd398f50aed09053b818463f901d7a7c80f4/src/portfolio/loader_history.py#L110-L125

**Comment by WLM1ke** [comment]
Объеденил и поправил тесты. К сожалению в метод мало чего можно запихнуть: только выбор колонок и преобразования объемов к числам. Все остальное оставил в функции - иначе будет неправильно работать.

https://github.com/WLM1ke/PortfolioOptimizer/blob/0e29241afc24f1c2f68d08371ba9e74f751663f3/src/portfolio/loader_history.py#L105-L111

**Comment by epogrebnyak** [comment]
Уже хорошо, так понятнее становится.

**Comment by WLM1ke** [comment]
Закрывать можно?

**Comment by epogrebnyak** [comment]
Закрою сам, одну идею хочу попробовать.

**Comment by epogrebnyak** [comment]
Закрываем через b689a481bdbc668b5813087ab285a91850191d90
