### ISSUE TITLE
rename `dl` submodule

### ISSUE THREAD

**Issue by epogrebnyak** [WLM1ke/PortfolioOptimizer#25]
- [x] название [dl](https://github.com/WLM1ke/PortfolioOptimizer/tree/master/src/portfolio/dl) неудачное, надо переименовать
- [ ] что делает пустой подмодуль [load](https://github.com/WLM1ke/PortfolioOptimizer/tree/master/src/portfolio/load)?

**Comment by WLM1ke** [comment]
Я хотел для краткости - давай в download переименуем
Модуль load будет загружать данные из локальной версии и дополнять данными из download в соответсвии с #24

**Comment by WLM1ke** [comment]
Переименовал в download

**Comment by WLM1ke** [comment]
Если возражений нет - закрой ишью

**Comment by epogrebnyak** [comment]
load на фоне download не особо понятен, надо load переименовать во что-то - getter, например. Если он пустой то может и не нужен.

**Comment by WLM1ke** [comment]
Он стал заполняться — написал предварительную версию модуля загрузки котировок из локальной версии и их обновление. Getter обычно что называют?

**Comment by WLM1ke** [comment]
Переименовал load в getter
