### ISSUE TITLE
Реализовать базовый класс портфеля

### ISSUE THREAD

**Issue by WLM1ke** [WLM1ke/PortfolioOptimizer#33]
**Конструктор:**
- Набор тикеров и лотов (словарь)
- Объём кэша
- Дата и стоимость - используются для проверки корректности данных (отклонение расчетной стоимости не должно сильно отличаться от введённой)

**Данные:**
- Дата формирования портфеля
- Тикеры (кэш специальный тикер с ценой 1 и портфель специальный тикер с количеством 1)
- Лоты
- Размеры лотов
- Краткие названия
- Стоимость/цены/веса бумаг закрытия на дату формирования портфеля
- Текущая стоимость/цены/веса бумаг

**Методы:**
- Получить сводные данные по портфелю - без параметров
- Если передан массив меток, то информация по указанным в метках параметрам

**Comment by epogrebnyak** [comment]
Может как-то попонятнее реализовать? похоже, что это класс просто создает фрейм с данными по параметрам позиций и наличности, почему так витьевато внутри? что такое `value=3_728_568.41`?

**Comment by WLM1ke** [comment]
В [числах можно _](https://www.python.org/dev/peps/pep-0515/) ставить для удобства разделения разрядов.
Может и можно по понятнее, но я не знаю как:)

**Comment by epogrebnyak** [comment]
`value` имелось ввиду - что это? контрольная сумма портфеля?

и какое действие закладывалось - создать массив котировок? это же просто задача работы с несколькими фреймами, тут даже класс не очень нужен.

**Comment by epogrebnyak** [comment]
У тебя раньше были более детальные докстринги, а сейчас общие форулировки - "содержит данные".
Я предлагаю потоптаться над описанием что класс должен делать, написать псеводо код и потом переделать в более простой класс или функции. 

Это состав портфеля, правильно:
- Набор тикеров и лотов (словарь) 
- Объём кэша

Это его расчетная величина, которую надо проверить:
- Дата и стоимость - используются для проверки корректности данных (отклонение расчетной стоимости не должно сильно отличаться от введённой)

Функционал:
- пересчитать стоимость портфеля на другую дату?

Что хочешь посчитать? ;)

**Comment by WLM1ke** [comment]
'value' - стоимость портфеля на некую дату, она нужна для проверки, что расчетная величина на основании отдельных позиций совпадает со стоимостью, которую рассчитал брокер.

Наверное можно набором функций, просто для всех этих функций нужны одни и тоже данные по позициям, взаимосвязь не всегда прямая. Мне показалось, что это легче в одном датафрейме собрать.

**Comment by WLM1ke** [comment]
# Описание

Это состав портфеля:
- Набор тикеров и лотов (словарь) 
- Объём кэша
- Дата, на которую представлена информация

Дополнительный параметр:
- Стоимость - используются для проверки корректности данных (отклонение расчетной стоимости не должно сильно отличаться от введённой)

Функционал - расчет следующих показателей на дату и по последним котировкам:
- Стоимость портфеля и отдельных позиций
- Доли позиций в портфеле

**Comment by epogrebnyak** [comment]
Задача на низовом уровне сводится к тому, чтобы по словарю `allocation` <тикеры (включая кэш)-лоты> на дату `date` считать стоимость позиций и портфеля в целом?

```
def create_portfolio(allocation, date):
    pass
    # return dataframe 

```

**Comment by WLM1ke** [comment]
Да, но кроме стоимости портфеля на дату нужны веса позиций в портфеле. 

Расчёт (стоимостей и долей) нужен не только на дату, которая передана, но и по самым последним котировкам.

**Comment by epogrebnyak** [comment]
> Расчёт (стоимостей и долей) нужен не только на дату, которая передана, но и по самым последним котировкам.

Наверное можем считать 'самые последние котировки' частным вариантом даты? 
Есть объект - фрейм на дату, дата может  быть в прошлом, может быть текущей, верно? 

> Да, но кроме стоимости портфеля на дату нужны веса позиций в портфеле.

Это выглядит как плюс один столбик в фрейме.

**Comment by WLM1ke** [comment]
> Наверное можем считать 'самые последние котировки' частным вариантом даты?
> Есть объект - фрейм на дату, дата может быть в прошлом, может быть текущей, верно?

Можно наверное и так - просто последнии цены несколько другой источник имеют (они меняются внутри дня), а прошлые фиксированы на конец дня.

> Это выглядит как плюс один столбик в фрейме.
Да, так я примерно и делал.
