### ISSUE TITLE
Все функции пакета Getter должны иметь аргумент - набор тикеров, а не отдельный тикер

### ISSUE THREAD

**Issue by WLM1ke** [WLM1ke/PortfolioOptimizer#34]

**Comment by epogrebnyak** [comment]
В README.md может поправить:

 Функции максимально приближены к API выдачи данных, поэтому принимают
разнародные аргументы - иногда набор тикеров, а иногда отдельный тикер:

Запутывает - особой разнородности нет, ну иногда список, ну иногда тикер,
ничего страшного.


2018-03-17 8:09 GMT+03:00 WLMike <notifications@github.com>:

**Comment by WLM1ke** [comment]
Поправил на "Функции максимально приближены к API выдачи данных, поэтому принимают иногда набор тикеров, а иногда отдельный тикер"
