### ISSUE TITLE
убрать *_from_start() из API конечного пользователя

### ISSUE THREAD

**Issue by epogrebnyak** [WLM1ke/PortfolioOptimizer#35]
Свежим взглядом - мое предложение насчет двух функций сейчас мне кажется перегружает понимание функций. Предлагаю для конечного пользователи оставить `quotes_history(ticker, start_date)` и `index_history(ticker, start_date)`, где `start_date` - опциональный.  Внутри кода можно использовать *_from_start() функции. 

> История котировок акций источник данных - quotes_history(ticker, start_date) и index_history_from_start(ticker)
> Итория значений индекса MOEX Russia Net Total Return (Resident) источник данных - index_history(ticker, start_date) и index_history_from_start(ticker)

**Comment by WLM1ke** [comment]
Мне кажется, тогда их можно полностью уж убрать???
