### ISSUE TITLE
отделить логику создания, обновления и чтения данных

### ISSUE THREAD

**Issue by epogrebnyak** [WLM1ke/PortfolioOptimizer#43]
https://github.com/WLM1ke/PortfolioOptimizer/blob/121e507e43627031797be6985a35d615aa68d96c/src/portfolio/getter/local_dividends.py#L36-L44

**Comment by epogrebnyak** [comment]
https://github.com/WLM1ke/PortfolioOptimizer/blob/121e507e43627031797be6985a35d615aa68d96c/src/portfolio/getter/local_cpi.py#L84-L91

**Comment by WLM1ke** [comment]
Жень, можешь поглядеть ответы и встречные вопросы

https://github.com/WLM1ke/PortfolioOptimizer/blob/master/src/portfolio/settings.py
https://github.com/WLM1ke/PortfolioOptimizer/blob/master/src/portfolio/getter/local_cpi.py
https://github.com/WLM1ke/PortfolioOptimizer/blob/master/src/portfolio/getter/local_dividends.py

**Comment by epogrebnyak** [comment]
также не очень понял как и зачем настроен 100 coverage

**Comment by WLM1ke** [comment]
Покрытие настраивается в этом [файле](https://github.com/WLM1ke/PortfolioOptimizer/blob/master/.coveragerc).
По поводу твоих комментариев возникли дополнительные вопросы:
- fecbe41070b397a4cfaf27ab6c7e6bcef4927121
- 634e3fdfe881cb152e4c03e98a3d437d7e8878e7
- 334f5357fe728af38201211cfa02ae670254760d

**Comment by epogrebnyak** [comment]
>По поводу твоих комментариев возникли дополнительные вопросы:
>    fecbe41
>    634e3fd
>    334f535

 прокомментировал в коммитах

**Comment by epogrebnyak** [comment]
Предлагаю local_cpi.py в этом ишью рефакторить, жду изменений от тебя

**Comment by WLM1ke** [comment]
Мне как-то не очень нравится эта идея:
- Функцию `is_updated(self)` практически для всех данных прийдется переопределять 
- Функцию `read_dataframe(self)` нужно как-то передавать конвертор с верхнего уровня

И получается, что только `save_dataframe(self, df)` претендует на какую-то универсальность на уровне "доступа к файлу" все остальное будет переопределяться в увязке с уровнем "логических операций по его обновлению". 

Есть ли смысл в таком разделении?

**Comment by WLM1ke** [comment]
Переписал [local_cpi](https://github.com/WLM1ke/PortfolioOptimizer/blob/master/src/optimizer/getter/local_cpi.py)
