### ISSUE TITLE
доп. данные по дивидендам

### ISSUE THREAD

**Issue by epogrebnyak** [WLM1ke/PortfolioOptimizer#46]
надо ли для проверки парсить эти данные по дивидендам?

https://www.moex.com/ru/listing/dividend-yield.aspx

**Comment by WLM1ke** [comment]
Нет - эти данные не интересны, тут дивидендная доходность считается от какой-то медианой цены за период. Интересны именно сами дивиденды, желательно привязанные к датам отсечек. А уж на нужную цену я сам поделю.
